[project]
name = "mysterybox-discord-bot"
version = "0.1.0"
description = "MysteryBox Discord bot for managing timed giveaways with random prizes"
requires-python = ">=3.11"
dependencies = [
    "discord-py>=2.5.2",
    "python-dotenv>=1.1.0",
    "aiohttp>=3.8.6",
]
